### ISSUE TITLE
Expose Capture::GraphicsCaptureSession::IsSupported()

### ISSUE THREAD

**Issue by clearlysid** [NiiightmareXD/windows-capture#2]
Hello, I'm making a cross-platform screen capture library and one thing that will be very useful is if the `Capture::GraphicsCaptureSession::IsSupported()` is exposed from within this crate. It would allow me to entirely omit my dependency on the windows::Graphics::Capture module and use `windows-capture` for everything 🙌

This would allow developers to check for API support independently instead of accounting for an error during capture.

I'm happy to make a PR for this if you let me know where to start.

Thanks for the fab work! 🌟

**Comment by NiiightmareXD** [comment]
Done, in v1.0.21 [GraphicsCaptureApi::is_supported()](https://docs.rs/windows-capture/latest/windows_capture/graphics_capture_api/struct.GraphicsCaptureApi.html#method.is_supported), Also there is [WindowsCaptureError](https://docs.rs/windows-capture/latest/windows_capture/graphics_capture_api/enum.WindowsCaptureError.html#) that shows if the [start()](https://docs.rs/windows-capture/latest/windows_capture/capture/trait.WindowsCaptureHandler.html#method.start) failed because the windows version is unsupported.

I'm going to add support for older Windows versions with DDA (probably going to be copied and pasted from [obs-studio](https://github.com/obsproject/obs-studio/blob/master/plugins/win-capture/window-capture.c))
